# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
  end

  config.vm.provision :shell, path: "bootstrap.sh"

  config.ssh.forward_agent = true
  config.ssh.forward_x11 = true
end
