#!/bin/sh
# postinst script for briar-desktop
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see https://www.debian.org/doc/debian-policy/ or
# the debian-policy package

case "$1" in
    configure)
ln -nsf /opt/briar-desktop/lib/briar-desktop-Briar.desktop /opt/briar-desktop/lib/org.briarproject.Briar.desktop
xdg-desktop-menu install --novendor /opt/briar-desktop/lib/org.briarproject.Briar.desktop
ln -nsf /opt/briar-desktop/bin/Briar /usr/bin/briar-desktop
ln -nsf /opt/briar-desktop/lib/app/resources/org.briarproject.Briar.metainfo.xml /usr/share/metainfo/org.briarproject.Briar.metainfo.xml
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
